### ISSUE TITLE
[Web] jwtのセッションorCookie管理

### ISSUE THREAD

**Issue by dyoshyy** [g-ohara/CurlARC-Web#7]

**Comment by g-ohara** [comment]
From [Selecting Session Management in Next.js](https://nextjs.org/docs/app/building-your-application/authentication#selecting-session-management-in-nextjs):

> Cookie-based sessions are simpler and suit smaller applications with lower server load but may offer less security. Database sessions, while more complex, provide better security and scalability, ideal for larger, data-sensitive applications.
